version: '2'
services:
  # LibreNMS
  librenms:
    build: ./build/librenms
    volumes:
      - ${COMPOSE_DOCKER_DATA}/${COMPOSE_PROJECT_NAME}/librenms/rrd:/opt/librenms/rrd
      - ${COMPOSE_DOCKER_CONFIG}/${COMPOSE_PROJECT_NAME}/librenms/configs:/configs/librenms
    environment:
      HOSTNAME: librenms
      LIBRENMS_AUTOUPDATE: "true"
      LIBRENMS_CONFIG_PHP_DBHOST: "db"
      LIBRENMS_CONFIG_PHP_DBUSER: "librenms"
      LIBRENMS_CONFIG_PHP_DBPASS: "l1br3nm5!"
      LIBRENMS_CONFIG_PHP_BASEURL: "https://${COMPOSE_DOCKER_SERVER_IP}"
      LIBRENMS_CONFIG_PHP_DB: "librenms"
      LIBRENMS_CONFIG_PHP_DBPORT: "3306"
#    extra_hosts:
#      - "librenms:127.0.0.1"
    ports:
      - "443:443"
      - "80:80"
    links:
      - "mariadb:db"
    networks:
      - main

  # MariaDB
  mariadb:
    build: ./build/mariadb
    volumes:
      - ${COMPOSE_DOCKER_DATA}/${COMPOSE_PROJECT_NAME}/mariadb/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_DATABASE: librenms
      MYSQL_USER: librenms
      MYSQL_PASSWORD: l1br3nm5!
    networks:
      - main

networks:
  main:
